In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v1", map_name="4x4") # create the environment

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# initialize all the Q-Learning Parameters
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1 # alpha --> a
discount_rate = 0.99 # gamma --> y

exploration_rate = 1 # epsilon --> e
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001 # test this number

In [6]:
 rewards_all_epsisodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()[0] # reset the environment
    done = False
    reward_current_episode = 0
    
    for step in range(max_steps_per_episode):
        # exploration vs exploitation
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) # exploit by picking the max q-value
        else:
            action = env.action_space.sample() # explore by taking a random action
        
        new_state, reward, done, info, prob = env.step(action) # take the action and retrieve the reward
        
        #Update the Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + \
            learning_rate*(reward + discount_rate*np.max(q_table[new_state, :]))
        # q_new(s,a) = (1-a)(q_old) + a(r_t1 + y*max(new_state, all actions)
        state = new_state
        reward_current_episode += reward
        
        if done:
            break
        
    rewards_all_epsisodes.append(reward_current_episode)
    # exploration decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
# calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_epsisodes), num_episodes/1000)
count = 1000
print("********Avearge reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# print updated Q-table
print(q_table)

********Avearge reward per thousand episodes********

1000 :  0.04400000000000003
2000 :  0.20500000000000015
3000 :  0.4250000000000003
4000 :  0.5520000000000004
5000 :  0.6330000000000005
6000 :  0.6590000000000005
7000 :  0.6720000000000005
8000 :  0.6720000000000005
9000 :  0.7040000000000005
10000 :  0.6740000000000005
[[0.45572504 0.44434114 0.44003083 0.44005485]
 [0.28876379 0.36339487 0.30239897 0.43202521]
 [0.38515878 0.39711944 0.37942261 0.40761067]
 [0.30704806 0.34898288 0.25132848 0.39775273]
 [0.46798214 0.33883471 0.27988371 0.24667553]
 [0.         0.         0.         0.        ]
 [0.27203639 0.24016632 0.23728247 0.18123544]
 [0.         0.         0.         0.        ]
 [0.44004081 0.38639157 0.43155969 0.49913891]
 [0.32832688 0.56935915 0.4864844  0.45640717]
 [0.53263322 0.3700591  0.36318903 0.3912215 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.52698543 0.47975473 0.72929979 0.53423266]
 [0.71484549 0.

In [7]:
env = gym.make("FrozenLake-v1", render_mode="human") # create the environment

In [8]:
for episode in range(3):
    state = env.reset()[0]
    done = False
    print("*****EPISODE ", episode+1, "******\n\n\n\n")
    time.sleep(5)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info, prob = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("*****You've reached the goal my son!******")
                time.sleep(3)
            else:
                print("*****You've fell in the hole, I'm dissapointed...******")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state

env.close()

*****You've reached the goal my son!******


KeyboardInterrupt: 